# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbba8503a434ad14ad4b14aec68fabb72355502a3943845030e66a6d7627e1466f8d103f76004b92c7fff052aca25cdba3ab18448c99b95a31c0816b20492918

test:
  secret_key_base: 9b85f86028bf5148fca3a36f0ec1194f452caaa87e1e212ef20e7c94d299a1cf5b3536fd5ed81c76171e27dbc1822c6da96902900464a72a6d3626e9bd89b8e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
